language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
notifications:
  email:
    on_success: always # [always|never|change] default: change
    on_failure: always # [always|never|change] default: always 